PACKAGE_NAME="hako-powerboard"
PACKAGE_VERSION="0.2.0"

BUILT_MODULE_NAME[0]="hako_powerboard"
BUILT_MODULE_LOCATION[0]="src"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hwmon"

MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/src modules"

AUTOINSTALL="yes"
